version: '3.1'

services:
  postgresdb:
    container_name: postgresdb
    image: postgres:13.5
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: credito_auto
    volumes:
      - credito-auto-pgsql-data:/var/lib/postgresql/data
    networks:
      - docker_network

  ca-msa-creditoauto:
    container_name: ca-msa-creditoauto
    image: robertcabrerapichincha/ca-msa-creditoauto:latest
    restart: always
    ports:
      - '8080:8080'
    networks:
      - docker_network
    depends_on:
      - postgresdb

networks:
  docker_network:
    driver: bridge

volumes:
  credito-auto-pgsql-data: